title: "CochetopaCo"
description: "Hobbies and Side Projects"
url: "https://www.cochetopa.co"
baseurl: ""       # leave blank if serving from the apex domain
logo: /assets/images/logo.avif
author:
  name: "Parker Hopkins (mtntheman)"
  email: "parker.a.hopkins@gmail.com"

#theme: none       # Because Awesome Jekyll is included as local files, not a gem

markdown: kramdown    # Default; ensure code fences and math support are enabled

##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true
  games:
    output: true
    permalink: /games/:path/


##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  # email: "example@example.cl"
  github: "https://github.com/a-chacon"
  # telegram: "https://t.me/"
  # stackoverflow: "https://stackoverflow.com"
  # discord: "https://discord.com/"
  # mastodon: "https://lile.cl/"

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
