on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}       # ← use built-in token
          config-file: .release-please-config.json

      - name: Setup Ruby & Publish Gem
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Release Gem
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: rubygems/release-gem@v1
